hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

server:
  port: 8082

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/


